In [17]:
num = 1
n = []  
def jisuan(num):
    decom = []
    while num:
        decom.append(num%10)
        num = num // 10
    res = 0
    for i in decom:
        res += i * i
    return res

In [18]:
n.append(num)
res = jisuan(num)
while True:
    if res == 1:
        print('true')
        break 
    else:
        if res in n:
            print('False')
            break
        else:
            n.append(res)
            res = jisuan(res)

true


In [19]:
import numpy as np

In [24]:
a = [1,2,3]
b = 2 * a

In [25]:
b

[1, 2, 3, 1, 2, 3]

In [26]:
a = (1,2,3)
b = 2 * a

In [27]:
b

(1, 2, 3, 1, 2, 3)

In [28]:
x = np.array([1,2,3])

In [29]:
2 * x

array([2, 4, 6])

In [35]:
x = np.arange(16).reshape(4,4)

In [36]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
2 * x

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [38]:
x*-1

array([[  0,  -1,  -2,  -3],
       [ -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11],
       [-12, -13, -14, -15]])

In [39]:
np.abs(x)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
np.sin(x)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [41]:
np.cos(x)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [42]:
np.tan(x)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02],
       [-6.35859929e-01,  4.63021133e-01,  7.24460662e+00,
        -8.55993401e-01]])

In [44]:
np.exp(x)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [45]:
np.power(3,x)

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]], dtype=int32)

In [46]:
np.power(x,3)

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331],
       [1728, 2197, 2744, 3375]], dtype=int32)

In [47]:
np.log(x)

f:\anaconda3\envs\haha\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [48]:
np.log2(x+1)

array([[0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        ],
       [3.169925  , 3.32192809, 3.45943162, 3.5849625 ],
       [3.70043972, 3.80735492, 3.9068906 , 4.        ]])

In [49]:
np.log10(x+1)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125],
       [1.11394335, 1.14612804, 1.17609126, 1.20411998]])

In [50]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [51]:
B = np.full((2,2),10)

In [52]:
B

array([[10, 10],
       [10, 10]])

In [53]:
A + B

array([[10, 11],
       [12, 13]])

In [54]:
A * B

array([[ 0, 10],
       [20, 30]])

In [55]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [56]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [57]:
A.T

array([[0, 2],
       [1, 3]])

In [58]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [59]:
A.dot(np.linalg.inv(A))

array([[1., 0.],
       [0., 1.]])

In [60]:
x = np.arange(16).reshape(2,8)

In [61]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [65]:
pinvx = np.linalg.pinv(x)

In [66]:
x.dot(pinvx)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])